# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site
name: UnimportantDistance
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
logo: 'assets/images/logo.png'
favicon: 'favicon.png'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samgrant.github.io" # the base hostname & protocol for your site, e.g. http://example.com
future: true

# social links
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate

remote_theme: jekyll/minima

paginate: 4
paginate_path: "/blog/page:num/"


# Collections
collections:
  authors:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"     
  - scope:
      path: ""
    values:
      layout: "base"